import { MigrationInterface, QueryRunner } from "typeorm";

export class  $npmConfigName1783348485629 implements MigrationInterface {
    name = ' $npmConfigName1783348485629'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "comment" character varying, "type" character varying, "rating" integer NOT NULL, "issues" json, "productId" uuid, "userId" uuid, CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a6b3c434392f5d10ec17104366" ON "reviews"  ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ed5659e7139fc8bc039198cc1" ON "reviews"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "quantity" integer NOT NULL DEFAULT '1', "price" numeric(15,5) NOT NULL, "discountedPrice" numeric(15,5), "cartId" uuid NOT NULL, "productId" uuid NOT NULL, CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72679d98b31c737937b8932ebe" ON "cart_items"  ("productId") `);
        await queryRunner.query(`CREATE TABLE "cart" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "userId" uuid NOT NULL, "itemsPrice" numeric NOT NULL DEFAULT '0', "shippingPrice" numeric NOT NULL DEFAULT '0', "totalPrice" numeric NOT NULL DEFAULT '0', "totalDiscount" numeric NOT NULL DEFAULT '0', "couponDiscount" numeric NOT NULL DEFAULT '0', "couponApplied" boolean NOT NULL DEFAULT false, "couponId" uuid, CONSTRAINT "PK_c524ec48751b9b5bcfbf6e59be7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "shipping_address" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "userId" uuid NOT NULL, "firstName" character varying NOT NULL, "lastName" character varying NOT NULL, "phone1" character varying NOT NULL, "phone2" character varying, "longitude" double precision, "latitude" double precision, "address" character varying NOT NULL, "lga" character varying NOT NULL, "postalCode" character varying, "state" character varying, "isDefault" boolean NOT NULL, CONSTRAINT "PK_facb0fff23b713c9e09b2da88f6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2aa99b101de6fb5f3089bd4b7a" ON "shipping_address"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "return_request" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "reason" character varying NOT NULL, "quantity" integer NOT NULL, "media" json, "address" json NOT NULL, "receipt" text NOT NULL, "comment" character varying NOT NULL, "adminComment" character varying, "decision" character varying, "code" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "dateApproved" character varying, "orderItemId" uuid NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "UQ_aad12e2d0945bf5dd913fbb9251" UNIQUE ("code"), CONSTRAINT "REL_b092d5a853242c11236ee7e998" UNIQUE ("orderItemId"), CONSTRAINT "PK_27b4fb62d047bfc2259c2ae4d64" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b092d5a853242c11236ee7e998" ON "return_request"  ("orderItemId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c80ea3f41097dbcda1eec4a56a" ON "return_request"  ("userId") `);
        await queryRunner.query(`CREATE TABLE "order_item" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "merchantId" uuid, "productId" uuid, "qty" integer NOT NULL, "image" character varying, "orderItemCode" character varying, "price" numeric(10,2) NOT NULL, "discountedPrice" numeric(15,5), "commission" numeric(15,5), "sellerBusinessName" text NOT NULL, "imeiNumber" character varying, "shipmentCode" character varying, "deliveryCode" character varying, "status" character varying DEFAULT 'pending', "orderId" uuid, CONSTRAINT "PK_d01158fe15b1ead5c26fd7f4e90" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f4f565b2a749f331fa8b8264c9" ON "order_item"  ("merchantId") `);
        await queryRunner.query(`CREATE TABLE "orders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "transactionId" character varying(255), "paymentMethod" character varying NOT NULL, "shippingFee" numeric NOT NULL DEFAULT '0', "orderSource" character varying DEFAULT 'ONLINE', "orderStatus" character varying DEFAULT 'pending', "discount" numeric NOT NULL DEFAULT '0', "subtotal" numeric NOT NULL DEFAULT '0', "grandTotal" numeric NOT NULL DEFAULT '0', "trackingNumber" character varying(255), "shipmentStatus" character varying(100), "shipmentCode" character varying(100), "shipmentCodeUsed" boolean NOT NULL DEFAULT false, "deliveryCode" character varying(100), "deliveryCodeUsed" boolean NOT NULL DEFAULT false, "paidAt" TIMESTAMP, "deliveredAt" TIMESTAMP, "userId" uuid NOT NULL, "shippingAddressId" uuid, "couponId" uuid, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "code" character varying NOT NULL, "name" character varying, "type" character varying, "description" character varying, "pricingRule" json, "discount" numeric NOT NULL, "maxUsage" integer, "usedCount" integer, "validFrom" TIMESTAMP, "validTo" TIMESTAMP, CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e025109230e82925843f2a14c4" ON "coupons"  ("code") `);
        await queryRunner.query(`CREATE TABLE "sections" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, CONSTRAINT "UQ_b43359623c10ff3d0a199289b8d" UNIQUE ("name"), CONSTRAINT "PK_f9749dd3bffd880a497d007e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "image" character varying(255), "commision" numeric(15,5) NOT NULL DEFAULT '2', "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "mpath" character varying DEFAULT '', "sectionId" integer NOT NULL, "parentId" integer, CONSTRAINT "UQ_420d9f679d41281f282f5bc7d09" UNIQUE ("slug"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_420d9f679d41281f282f5bc7d0" ON "categories"  ("slug") `);
        await queryRunner.query(`CREATE INDEX "idx_category_section" ON "categories"  ("sectionId") `);
        await queryRunner.query(`CREATE INDEX "idx_category_parent" ON "categories"  ("parentId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "idx_category_slug" ON "categories"  ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."products_status_enum" AS ENUM('LIVE', 'IN_REVIEW', 'NOT_APPROVED')`);
        await queryRunner.query(`CREATE TABLE "products" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "productName" text NOT NULL, "merchantId" uuid, "businessId" uuid, "actual_price" numeric(15,5), "discounted_price" numeric(15,5), "discount" numeric(10,4) NOT NULL DEFAULT '0', "images" json, "rating" numeric(5,2) NOT NULL DEFAULT '0', "brand" character varying(255) NOT NULL, "description" text NOT NULL, "specification" json, "model" character varying(255), "weight" character varying(255), "color" json, "quantity" integer NOT NULL DEFAULT '0', "hasWarranty" boolean NOT NULL DEFAULT false, "warranty" character varying(100), "erpItemCode" character varying(255), "erpSKUNumber" character varying(100), "slug" text NOT NULL, "status" "public"."products_status_enum" NOT NULL DEFAULT 'IN_REVIEW', "commission" numeric(15,5) DEFAULT '0', "commissionPercentage" numeric(10,4) NOT NULL DEFAULT '0', "categoryId" integer NOT NULL, CONSTRAINT "UQ_464f927ae360106b783ed0b4106" UNIQUE ("slug"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ff56834e735fa78a15d0cf2192" ON "products"  ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7139c20741319eaa68e7fac20e" ON "products"  ("merchantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_359bd8406fbfb50e3ea42b5631" ON "products"  ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_464f927ae360106b783ed0b410" ON "products"  ("slug") `);
        await queryRunner.query(`CREATE TABLE "business_profile" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "name" character varying(255) NOT NULL, "address" character varying(255) NOT NULL, "phone" character varying(255), "email" character varying(255), "website" character varying(255), "logo" character varying(255), "businessType" character varying(255) NOT NULL, "businessCategory" json NOT NULL, "businessSection" json, "businessLocationLat" double precision, "businessLocationLong" double precision, "accountName" character varying(255), "accountNumber" character varying(255), "bankName" character varying(255), "bankCode" character varying(255), "document" character varying(500), "ownerId" uuid, CONSTRAINT "PK_e71e197c467c1ec2c45a1652110" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wishlists" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "userId" uuid, CONSTRAINT "PK_d0a37f2848c5d268d315325f359" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "warranty" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "imei" character varying(255) NOT NULL, "brand_model" character varying NOT NULL, "address" character varying NOT NULL, "area" character varying NOT NULL, "phone" character varying NOT NULL, "claimant" character varying NOT NULL, "warrantyStatus" character varying NOT NULL DEFAULT 'EXPIRED', "isWarrantyClaimed" boolean NOT NULL DEFAULT false, "warrantyExpiryDate" TIMESTAMP NOT NULL, "pickupDate" character varying NOT NULL, "pickupTime" character varying NOT NULL, "deviceIssue" text NOT NULL, "claimDetails" jsonb NOT NULL, "userId" uuid NOT NULL, CONSTRAINT "PK_33943757e620d2c5a0f143ad22e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('pending', 'approved', 'rejected', 'inactive', 'active', 'banned')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "username" character varying(255), "firstName" character varying(255), "middleName" character varying(255), "lastName" character varying(255), "email" character varying(255), "googleId" character varying(255), "password" character varying(255) DEFAULT 'PLACEHOLDER_PASSWORD', "countryCode" character varying, "phone" character varying(20), "postalCode" character varying, "profilePhoto" character varying, "phone2" character varying(20), "gender" character varying(20), "address" character varying, "role" character varying, "region" character varying, "fcmToken" character varying(255), "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "isActivated" boolean NOT NULL DEFAULT false, "emailVerified" boolean NOT NULL DEFAULT false, "isBanned" boolean NOT NULL DEFAULT false, "ipAddress" character varying, "newsLetterMail" character varying(255), "subscribedToNewsletter" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "UQ_f382af58ab36057334fb262efd5" UNIQUE ("googleId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ace513fa30d485cfd25c11a9e4" ON "users"  ("role") `);
        await queryRunner.query(`CREATE INDEX "IDX_1cd8a0b08c6c4f1d66e2f74071" ON "users"  ("phone", "phone2") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_630a929bfca852d724cb66820b" ON "users"  ("email", "role") `);
        await queryRunner.query(`CREATE TABLE "otps" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "otp" character varying(6) NOT NULL, "expiry" TIMESTAMP WITH TIME ZONE NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, "purpose" character varying, "userId" uuid NOT NULL, CONSTRAINT "PK_91fef5ed60605b854a2115d2410" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "brands" ("id" SERIAL NOT NULL, "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "category" character varying(255), "image" character varying(255), "description" character varying(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_b15428f362be2200922952dc268" UNIQUE ("slug"), CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mobile_banner" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_7cbc259ac8a87a6ceb925ccaad1" UNIQUE ("name"), CONSTRAINT "PK_d1ec35cbc90b9122e1da054dc5d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "mobile_banner_images" ("id" SERIAL NOT NULL, "imageUrl" character varying NOT NULL, "altText" character varying, "bannerId" integer, CONSTRAINT "PK_a07b6bec6f837faf9033da76c2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "web_banner" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_f3e69392f846efe1604301b283f" UNIQUE ("name"), CONSTRAINT "PK_37d80df081af7c6fce2b7b4708a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "web_banner_images" ("id" SERIAL NOT NULL, "imageUrl" character varying NOT NULL, "altText" character varying, "bannerId" integer, CONSTRAINT "PK_b47df461eb83dce6c61f1db594a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "balance" double precision NOT NULL DEFAULT '0', "totalCredit" double precision NOT NULL DEFAULT '0', "totalDebit" double precision NOT NULL DEFAULT '0', "userId" uuid NOT NULL, CONSTRAINT "UQ_2ecdb33f23e9a6fc392025c0b97" UNIQUE ("userId"), CONSTRAINT "UQ_2ecdb33f23e9a6fc392025c0b97" UNIQUE ("userId"), CONSTRAINT "REL_2ecdb33f23e9a6fc392025c0b9" UNIQUE ("userId"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2ecdb33f23e9a6fc392025c0b9" ON "wallets"  ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'PENDING_ESCROW', 'IN_ESCROW', 'RELEASING', 'DISPUTED')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('EXTERNAL_DEPOSIT', 'PAYMENT', 'ESCROW', 'ESCROW_RELEASE', 'REFUND', 'ESCROW_REFUND', 'WITHDRAWAL_REQUEST', 'WITHDRAWAL_PROCESSING', 'WITHDRAWAL_COMPLETED', 'WITHDRAWAL_FAILED', 'FEE_COLLECTION', 'ADJUSTMENT')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "amount" double precision NOT NULL, "reference" text NOT NULL, "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'PENDING', "type" "public"."transactions_type_enum" NOT NULL DEFAULT 'PAYMENT', "fromWalletId" uuid, "toWalletId" uuid, "fee" double precision DEFAULT '0', "description" text, "metadata" json, "externalReference" character varying, "paymentProvider" character varying, "orderId" uuid, "releaseDate" TIMESTAMP, CONSTRAINT "UQ_dd85cc865e0c3d5d4be095d3f3f" UNIQUE ("reference"), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_dd85cc865e0c3d5d4be095d3f3" ON "transactions"  ("reference") `);
        await queryRunner.query(`CREATE TYPE "public"."escrow_payments_status_enum" AS ENUM('HELD', 'RELEASED', 'CANCELLED', 'REFUNDED', 'DISPUTED')`);
        await queryRunner.query(`CREATE TABLE "escrow_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "amount" double precision NOT NULL, "status" "public"."escrow_payments_status_enum" NOT NULL DEFAULT 'HELD', "releaseDate" TIMESTAMP NOT NULL, "releasedAt" TIMESTAMP, "transactionId" uuid, "merchantId" uuid, "orderItemId" uuid, "releaseTransactionId" uuid, CONSTRAINT "REL_2b1f9833404a33f110dc7cffd4" UNIQUE ("releaseTransactionId"), CONSTRAINT "PK_42d6fc9c8de9ad82b6c594f5a47" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "waitlist" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "fullName" character varying(255) NOT NULL, "phone" character varying(255) NOT NULL, "email" character varying NOT NULL, CONSTRAINT "UQ_2221cffeeb64bff14201bd5b3de" UNIQUE ("email"), CONSTRAINT "PK_973cfbedc6381485681d6a6916c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "third_party_warranty" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "imei" character varying(255) NOT NULL, "name" character varying NOT NULL, "email" character varying NOT NULL, CONSTRAINT "UQ_5071bc758bc8569bdf9676e23b9" UNIQUE ("email"), CONSTRAINT "PK_c668c145f40c480ae5043cb7767" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."system_wallets_type_enum" AS ENUM('PLATFORM_ESCROW', 'PLATFORM_FEE', 'OPERATING')`);
        await queryRunner.query(`CREATE TABLE "system_wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP WITH TIME ZONE, "meta" json, "name" character varying NOT NULL, "type" "public"."system_wallets_type_enum" NOT NULL, "balance" double precision NOT NULL DEFAULT '0', CONSTRAINT "PK_e0116b124c5493d161969feda1c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products_coupons_coupons" ("productsId" uuid NOT NULL, "couponsId" uuid NOT NULL, CONSTRAINT "PK_0daaef781962f3994ad9861e6b1" PRIMARY KEY ("productsId", "couponsId"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d9583989a5578fb727177ef99d" ON "products_coupons_coupons"  ("productsId") `);
        await queryRunner.query(`CREATE INDEX "IDX_b81eab05a184e2affdc1ffff9f" ON "products_coupons_coupons"  ("couponsId") `);
        await queryRunner.query(`CREATE TABLE "wishlist_products" ("wishlist_id" uuid NOT NULL, "product_id" uuid NOT NULL, CONSTRAINT "PK_1f0be74788ce11fb7abf6b454e5" PRIMARY KEY ("wishlist_id", "product_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8591f054ca150d438b1d9a0ff1" ON "wishlist_products"  ("wishlist_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_3535698ebff0eba82f02f1df22" ON "wishlist_products"  ("product_id") `);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a6b3c434392f5d10ec171043666" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "cart"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_72679d98b31c737937b8932ebe6" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_756f53ab9466eb52a52619ee019" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart" ADD CONSTRAINT "FK_b587940e6e9cfec985552e6709b" FOREIGN KEY ("couponId") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "shipping_address" ADD CONSTRAINT "FK_2aa99b101de6fb5f3089bd4b7a9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_request" ADD CONSTRAINT "FK_b092d5a853242c11236ee7e9987" FOREIGN KEY ("orderItemId") REFERENCES "order_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "return_request" ADD CONSTRAINT "FK_c80ea3f41097dbcda1eec4a56a6" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_904370c093ceea4369659a3c810" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_item" ADD CONSTRAINT "FK_f4f565b2a749f331fa8b8264c99" FOREIGN KEY ("merchantId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_cc4e4adab232e8c05026b2f345d" FOREIGN KEY ("shippingAddressId") REFERENCES "shipping_address"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_c26db6c65929ecfeab91073e80c" FOREIGN KEY ("couponId") REFERENCES "coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_477fa738bfc297a7bebb3b6b876" FOREIGN KEY ("sectionId") REFERENCES "sections"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa" FOREIGN KEY ("parentId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_7139c20741319eaa68e7fac20ed" FOREIGN KEY ("merchantId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_359bd8406fbfb50e3ea42b5631f" FOREIGN KEY ("businessId") REFERENCES "business_profile"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_profile" ADD CONSTRAINT "FK_8c949cadd1a7ec63f53aa8df7dd" FOREIGN KEY ("ownerId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlists" ADD CONSTRAINT "FK_4f3c30555daa6ab0b70a1db772c" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warranty" ADD CONSTRAINT "FK_b670b42039df9917999560138e4" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otps" ADD CONSTRAINT "FK_82b0deb105275568cdcef2823eb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "mobile_banner_images" ADD CONSTRAINT "FK_3ff9846475d1fcda7d59dde91d8" FOREIGN KEY ("bannerId") REFERENCES "mobile_banner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "web_banner_images" ADD CONSTRAINT "FK_023c7fafd71092ebc1cc009c238" FOREIGN KEY ("bannerId") REFERENCES "web_banner"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_4e9fd0fae0b15072b3ba91b3dcd" FOREIGN KEY ("fromWalletId") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_8ae6618f9e901745e70f8828ec8" FOREIGN KEY ("toWalletId") REFERENCES "wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_2fdbbae70ff802bc8b703ee7c5c" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_payments" ADD CONSTRAINT "FK_ac24b8e940a8556c156fa8259fd" FOREIGN KEY ("transactionId") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_payments" ADD CONSTRAINT "FK_5a8bb0125af01bbfc098b1ce0c0" FOREIGN KEY ("merchantId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_payments" ADD CONSTRAINT "FK_a93d0cd08776869a055b6daf085" FOREIGN KEY ("orderItemId") REFERENCES "order_item"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "escrow_payments" ADD CONSTRAINT "FK_2b1f9833404a33f110dc7cffd48" FOREIGN KEY ("releaseTransactionId") REFERENCES "transactions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products_coupons_coupons" ADD CONSTRAINT "FK_d9583989a5578fb727177ef99df" FOREIGN KEY ("productsId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "products_coupons_coupons" ADD CONSTRAINT "FK_b81eab05a184e2affdc1ffff9ff" FOREIGN KEY ("couponsId") REFERENCES "coupons"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wishlist_products" ADD CONSTRAINT "FK_8591f054ca150d438b1d9a0ff12" FOREIGN KEY ("wishlist_id") REFERENCES "wishlists"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "wishlist_products" ADD CONSTRAINT "FK_3535698ebff0eba82f02f1df22a" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "wishlist_products" DROP CONSTRAINT "FK_3535698ebff0eba82f02f1df22a"`);
        await queryRunner.query(`ALTER TABLE "wishlist_products" DROP CONSTRAINT "FK_8591f054ca150d438b1d9a0ff12"`);
        await queryRunner.query(`ALTER TABLE "products_coupons_coupons" DROP CONSTRAINT "FK_b81eab05a184e2affdc1ffff9ff"`);
        await queryRunner.query(`ALTER TABLE "products_coupons_coupons" DROP CONSTRAINT "FK_d9583989a5578fb727177ef99df"`);
        await queryRunner.query(`ALTER TABLE "escrow_payments" DROP CONSTRAINT "FK_2b1f9833404a33f110dc7cffd48"`);
        await queryRunner.query(`ALTER TABLE "escrow_payments" DROP CONSTRAINT "FK_a93d0cd08776869a055b6daf085"`);
        await queryRunner.query(`ALTER TABLE "escrow_payments" DROP CONSTRAINT "FK_5a8bb0125af01bbfc098b1ce0c0"`);
        await queryRunner.query(`ALTER TABLE "escrow_payments" DROP CONSTRAINT "FK_ac24b8e940a8556c156fa8259fd"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_2fdbbae70ff802bc8b703ee7c5c"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_8ae6618f9e901745e70f8828ec8"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_4e9fd0fae0b15072b3ba91b3dcd"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "web_banner_images" DROP CONSTRAINT "FK_023c7fafd71092ebc1cc009c238"`);
        await queryRunner.query(`ALTER TABLE "mobile_banner_images" DROP CONSTRAINT "FK_3ff9846475d1fcda7d59dde91d8"`);
        await queryRunner.query(`ALTER TABLE "otps" DROP CONSTRAINT "FK_82b0deb105275568cdcef2823eb"`);
        await queryRunner.query(`ALTER TABLE "warranty" DROP CONSTRAINT "FK_b670b42039df9917999560138e4"`);
        await queryRunner.query(`ALTER TABLE "wishlists" DROP CONSTRAINT "FK_4f3c30555daa6ab0b70a1db772c"`);
        await queryRunner.query(`ALTER TABLE "business_profile" DROP CONSTRAINT "FK_8c949cadd1a7ec63f53aa8df7dd"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_359bd8406fbfb50e3ea42b5631f"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_7139c20741319eaa68e7fac20ed"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_9a6f051e66982b5f0318981bcaa"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_477fa738bfc297a7bebb3b6b876"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_c26db6c65929ecfeab91073e80c"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_cc4e4adab232e8c05026b2f345d"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_f4f565b2a749f331fa8b8264c99"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_904370c093ceea4369659a3c810"`);
        await queryRunner.query(`ALTER TABLE "order_item" DROP CONSTRAINT "FK_646bf9ece6f45dbe41c203e06e0"`);
        await queryRunner.query(`ALTER TABLE "return_request" DROP CONSTRAINT "FK_c80ea3f41097dbcda1eec4a56a6"`);
        await queryRunner.query(`ALTER TABLE "return_request" DROP CONSTRAINT "FK_b092d5a853242c11236ee7e9987"`);
        await queryRunner.query(`ALTER TABLE "shipping_address" DROP CONSTRAINT "FK_2aa99b101de6fb5f3089bd4b7a9"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_b587940e6e9cfec985552e6709b"`);
        await queryRunner.query(`ALTER TABLE "cart" DROP CONSTRAINT "FK_756f53ab9466eb52a52619ee019"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_72679d98b31c737937b8932ebe6"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a6b3c434392f5d10ec171043666"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3535698ebff0eba82f02f1df22"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8591f054ca150d438b1d9a0ff1"`);
        await queryRunner.query(`DROP TABLE "wishlist_products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b81eab05a184e2affdc1ffff9f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9583989a5578fb727177ef99d"`);
        await queryRunner.query(`DROP TABLE "products_coupons_coupons"`);
        await queryRunner.query(`DROP TABLE "system_wallets"`);
        await queryRunner.query(`DROP TYPE "public"."system_wallets_type_enum"`);
        await queryRunner.query(`DROP TABLE "third_party_warranty"`);
        await queryRunner.query(`DROP TABLE "waitlist"`);
        await queryRunner.query(`DROP TABLE "escrow_payments"`);
        await queryRunner.query(`DROP TYPE "public"."escrow_payments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dd85cc865e0c3d5d4be095d3f3"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ecdb33f23e9a6fc392025c0b9"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TABLE "web_banner_images"`);
        await queryRunner.query(`DROP TABLE "web_banner"`);
        await queryRunner.query(`DROP TABLE "mobile_banner_images"`);
        await queryRunner.query(`DROP TABLE "mobile_banner"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP TABLE "otps"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_630a929bfca852d724cb66820b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cd8a0b08c6c4f1d66e2f74071"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace513fa30d485cfd25c11a9e4"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TABLE "warranty"`);
        await queryRunner.query(`DROP TABLE "wishlists"`);
        await queryRunner.query(`DROP TABLE "business_profile"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_464f927ae360106b783ed0b410"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_359bd8406fbfb50e3ea42b5631"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7139c20741319eaa68e7fac20e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff56834e735fa78a15d0cf2192"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TYPE "public"."products_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_category_slug"`);
        await queryRunner.query(`DROP INDEX "public"."idx_category_parent"`);
        await queryRunner.query(`DROP INDEX "public"."idx_category_section"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_420d9f679d41281f282f5bc7d0"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "sections"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e025109230e82925843f2a14c4"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f4f565b2a749f331fa8b8264c9"`);
        await queryRunner.query(`DROP TABLE "order_item"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c80ea3f41097dbcda1eec4a56a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b092d5a853242c11236ee7e998"`);
        await queryRunner.query(`DROP TABLE "return_request"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2aa99b101de6fb5f3089bd4b7a"`);
        await queryRunner.query(`DROP TABLE "shipping_address"`);
        await queryRunner.query(`DROP TABLE "cart"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72679d98b31c737937b8932ebe"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ed5659e7139fc8bc039198cc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6b3c434392f5d10ec17104366"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
    }

}
